function Hd = Highpass_filter
%HIGHPASS_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 29-Nov-2019 16:26:13

% Equiripple Highpass filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N     = 100;   % Order
Fstop = 0.48;  % Stopband Frequency
Fpass = 0.52;  % Passband Frequency
Wstop = 1;     % Stopband Weight
Wpass = 1;     % Passband Weight
dens  = 20;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop Fpass 1], [0 0 1 1], [Wstop Wpass], {dens});
Hd = dfilt.dffir(b);

% [EOF]
